version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "09:00"
          timezone: "Europe/Paris"
      groups:
          dependencies:
              patterns:
                  - "*"
      commit-message:
          prefix: "chore"
          prefix-development: "chore"
          include: "scope"
      open-pull-requests-limit: 10
      reviewers:
          - "${{secrets.GITHUB_ACTOR}}"
      labels:
          - "dependencies"
          - "automerge"
