name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.RELEASE_TOKEN }}

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Type check
              run: bun run typecheck

            - name: Lint
              run: bun run lint

            - name: Check formatting
              run: bun run format:check

            - name: Run tests
              run: bun test || echo "Aucun test configuré"

    security:
        runs-on: ubuntu-latest
        permissions:
            security-events: write
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.RELEASE_TOKEN }}

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  languages: javascript

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3
