name: Version Management

on:
    # Auto-increment patch version on push to main
    push:
        branches: [main]
        paths-ignore:
            - "package.json"
            - "package-lock.json"

    # Manual version bump via workflow dispatch
    workflow_dispatch:
        inputs:
            bump:
                description: "Type de bump de version"
                required: true
                default: "patch"
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    bump-version:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.RELEASE_TOKEN }}

            - name: Setup Node.js
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Configure Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Get current version
              id: current
              run: |
                  CURRENT_VERSION=$(node -p "require('./package.json').version")
                  echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

            - name: Determine version bump type
              id: bump_type
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    echo "type=${{ github.event.inputs.bump }}" >> $GITHUB_OUTPUT
                  else
                    echo "type=patch" >> $GITHUB_OUTPUT
                  fi

            - name: Bump version
              id: bump
              run: |
                  npm version ${{ steps.bump_type.outputs.type }} --no-git-tag-version
                  NEW_VERSION=$(node -p "require('./package.json').version")
                  echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
                  echo "tag=v$NEW_VERSION" >> $GITHUB_OUTPUT

            - name: Commit version update
              run: |
                  git add package.json package-lock.json
                  git commit -m "chore: bump version to ${{ steps.bump.outputs.version }}"
                  git tag ${{ steps.bump.outputs.tag }}
                  git push
                  git push --tags

            - name: Create commit summary
              run: |
                  echo "### Version mise à jour ✅" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "Version précédente: v${{ steps.current.outputs.version }}" >> $GITHUB_STEP_SUMMARY
                  echo "Nouvelle version: v${{ steps.bump.outputs.version }}" >> $GITHUB_STEP_SUMMARY
                  echo "Type de bump: ${{ steps.bump_type.outputs.type }}" >> $GITHUB_STEP_SUMMARY
